export const PayloadTypes = {
  REPLY_REPORT_YES: 'REPLY_REPORT_YES',
  REPLY_REPORT_NO: 'REPLY_REPORT_NO',
  REPLY_PICTURES_YES: 'REPLY_PICTURES_YES',
  REPLY_PICTURES_NO: 'REPLY_PICTURES_NO',
  REPLY_ANONYMOUS_YES: 'REPLY_ANONYMOUS_YES',
  REPLY_ANONYMOUS_NO: 'REPLY_ANONYMOUS_NO',
  HELP_CAFETERIA: 'HELP_CAFETERIA',
  HELP_SCHEDULE: 'HELP_SCHEDULE',
  HELP_REPORT: 'HELP_REPORT',
}
